# Generated by Django 2.2.28 on 2022-11-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addresslukvbbthlk'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresslukvbbthlk',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
